### ISSUE TITLE
dss operations within coupler pass an unused `t` argument. 

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaCoupler.jl#396] opened 2023-08-17 23:41 UTC
Following the `CTS` interface, the `weighted_dss_slab!` function definition requires a third `t` (time) argument which is unused within the `ClimaCore.Spaces.weighted_dss!` function. We may want to remove this from our general design pattern.

**Comment by LenkaNovak** [comment] 2023-08-18 02:09
@akshaysridhar @sriharshakandala @kmdeck 

As @gdecker1 found earlier, Float32 runs now break in ClimaLSM due to `t` being specified as an FT type [here](https://github.com/CliMA/ClimaLSM.jl/blob/076d04047eea206dff797072f48d60494ba43852/src/shared_utilities/utils.jl#L91), and for some reason FT is being returned as Float64 even if all arguments to the `ODEProblem` are passed as FT32. @dennisYatunin maybe you'll be familiar with the internals of this, do you think this could be an issue in ClimaTimeSteppers?

<img width="838" alt="Screen Shot 2023-08-17 at 6 59 30 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/0ac0f728-dfce-4a23-a31a-5d0ec214c23d">

For some reason our FT32 Buildkite was set with FT64, which is why we didn't catch this earlier! Error is reproducible if [the driver on this branch](https://github.com/CliMA/ClimaCoupler.jl/blob/ln/dss-ft-issue/experiments/AMIP/modular/coupler_driver_modular.jl) is run interactively. 

(Note, FT32 didn't cause problems in the Coupler before the ClimaLSM.dss! PR.  )

Unless we're doing something silly here, are you all happy to remove the type specification (like we did in the coupler #387) in ClimaLSM, before this issue gets resolved in ClimaTimeSteppers? As it stands, we can't test FT32 AMIP.

**Comment by akshaysridhar** [comment] 2023-08-18 15:53
Adding notes from Slack here: (`Callbacks` in the timestepping methods also require a `(u,p,t)` arg list)

**Comment by dennisYatunin** [comment] 2023-08-18 19:01
You should probably just drop the unnecessary `FT` type restriction. The type of `t` that comes here from the integrator does not matter because it should not be used for anything besides debugging. For now, `t` always needs to be stored as a `Float64` because `Float32` does not have enough bits to accurately track time without roundoff error.

**Comment by kmdeck** [comment] 2023-08-21 16:59
hi all - catching up here. 
is this correct: ClimaLSM needs a PR which drops the type restriction `t` in `dss!` but which keeps it as an argument.

We may need to do this in multiple functions because we had assumed that `t` would be the same type as that underlying the state vectors. In the past, I thought this was a desirable feature, that we wanted the type restriction to ensure the simulation took place entirely at float32 or at float64. But we will make the above change and see if we run into issues first.

**Comment by LenkaNovak** [comment] 2023-08-22 00:36
Hi @kmdeck , thanks for following up on this! 🚀 That's right! Looks like removing the type specification would be the quick (and probably only) fix. Thanks @dennisYatunin for the explanation. I agree that it would be better to have consistent types, but I also get the float precision issue. Do you guys have tests that run with Float32?

**Comment by kmdeck** [comment] 2023-08-22 15:40
> Hi @kmdeck , thanks for following up on this! 🚀 That's right! Looks like removing the type specification would be the quick (and probably only) fix. Thanks @dennisYatunin for the explanation. I agree that it would be better to have consistent types, but I also get the float precision issue. Do you guys have tests that run with Float32?

We have unit tests that run with Float32 but all of our integrations (in experiments, etc) use Float64, I think. Ill make sure we can run with Float32 before merging anything!

**Comment by kmdeck** [comment] 2023-08-24 17:45
> > Hi @kmdeck , thanks for following up on this! 🚀 That's right! Looks like removing the type specification would be the quick (and probably only) fix. Thanks @dennisYatunin for the explanation. I agree that it would be better to have consistent types, but I also get the float precision issue. Do you guys have tests that run with Float32?
> 
> We have unit tests that run with Float32 but all of our integrations (in experiments, etc) use Float64, I think. Ill make sure we can run with Float32 before merging anything!

@LenkaNovak it turns out that we have implicit requirements that t be the same float type as the state in a lot of places. so it will be a bigger change for us to get this to run. For example, whenever we prescribe time varying BC (reanalysis data, etc), the BC ends up being the same type as t, or a combination of quantities that are of type (t) and of the state FT). 

what is the priority on this?

**Comment by LenkaNovak** [comment] 2023-08-25 04:49
Hmm... I thought you guys don't use the `t` variable in the locally defined `dss!` function like [here](https://github.com/CliMA/ClimaLSM.jl/blob/ae8985563721f5d44d35b3907e08c077f9c5461d/src/shared_utilities/utils.jl#L91C1-L91C11). All we should need is for the `t::FT` to be changed to just `t` on that line.  Or is that not always the case? 🤔

**Comment by kmdeck** [comment] 2023-08-29 18:30
> Hmm... I thought you guys don't use the `t` variable in the locally defined `dss!` function like [here](https://github.com/CliMA/ClimaLSM.jl/blob/ae8985563721f5d44d35b3907e08c077f9c5461d/src/shared_utilities/utils.jl#L91C1-L91C11). All we should need is for the `t::FT` to be changed to just `t` on that line. Or is that not always the case? 🤔

The issue is actually that we assume t is the same type as the state in many places (not just here - also in time varying boundary conditions, using renalysis data, etc). We didnt adequately test running with Float32; I think since switching to ClimaTimesteppers we lost this capability.

**Comment by LenkaNovak** [comment] 2023-08-29 21:24
I see, thank you for looking into this, @kmdeck . I think Atmos has similar problems, but it was on their radar to re-enable single precision soon. As for the question on priorities, I'm not totally sure. @cmbengue @tapios How much should we prioritize Float32 runs right now?

**Comment by tapios** [comment] 2023-08-29 21:36
> I see, thank you for looking into this, @kmdeck . I think Atmos has similar problems, but it was on their radar to re-enable single precision soon. As for the question on priorities, I'm not totally sure. @cmbengue @tapios How much should we prioritize Float32 runs right now?

It depends on what right now means. It's not crucial, I think, for the 4-6 weeks or so. But beyond that, we'd like to be able to do coupled runs (on GPUs) in Float32.

**Comment by dennisYatunin** [comment] 2023-08-29 21:39
It's also worth noting that we will probably continue to avoid using `Float32` to represent `t`; it just leads to too much roundoff error for long simulations. The most viable options now are `Float64` and maybe also `DateTime` (though using the latter would require changing a lot of code where we assume that `t` is a number).

**Closed** 2024-10-14 21:44 UTC
Labels: :moneybag: Grab Bag, good first issue
