### ISSUE TITLE
GPU: replicate MPI functionality in the current slabplanet experiments

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#508] opened 2023-11-20 18:05 UTC
Make the slabplanet experiments CUDA compatible. 

- [ ] Replicate `comms_ctx` setup of [ClimaCore](https://github.com/CliMA/ClimaCore.jl/blob/546e102af5d447dc101eb17ddf5760e8ac8a9330/examples/hybrid/driver.jl#L30) or [ClimaAtmos](https://github.com/CliMA/ClimaAtmos.jl/blob/e9d8076e48e2abbeac79b3407c753b487a8678fb/src/solver/type_getters.jl#L674) in [mpi_init.jl](https://github.com/CliMA/ClimaCoupler.jl/blob/2a9b4aec94d407bedcb0b18ec7ef6cb41ac91f72/experiments/AMIP/modular/mpi/mpi_init.jl); turn warnings into structs that print outside of the GPU kernel)
- [ ] modify warnings in src if needed

**Comment by juliasloan25** [comment] 2024-01-24 00:03
duplicate of #530

**Closed by juliasloan25** 2024-01-24 00:03 UTC
Labels: :leaves: leaf, GPU
