### ISSUE TITLE
Fix land albedo regridding

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#764] opened 2024-05-01 05:49 UTC
This is the output of `CL.surface_albedo(sim.model, sim.integrator.u, sim.integrator.p)` when using `map_temporal`
<img width="376" alt="Screen Shot 2024-04-30 at 11 10 12 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/8b5566c5-d9d7-4a7d-8399-96bbd223554d">

We checked the original nc file and this seems to be fine:
<img width="546" alt="Screen Shot 2024-04-30 at 10 45 52 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/b5edf1ff-c9a5-49dc-a0f2-6f3f3b9cac0b">

This seems to be a problem in ClimaLand, but it would be good to check that this is still the case for the latest ClimaLand tag.

**Comment by Sbozzolo** [comment] 2024-05-04 01:08
A first look in ClimaUtilities shows no clear problems with TempestRemap:
![image](https://github.com/CliMA/ClimaCoupler.jl/assets/9167485/a42ad9bc-b046-46a2-bc31-f5ff48d2dbe9)

https://github.com/CliMA/ClimaUtilities.jl/issues/53

**Comment by Sbozzolo** [comment] 2024-05-04 23:26
This is from ClimaLand, `surface_albedo`, at the first iteration for our CI experiment
![image](https://github.com/CliMA/ClimaCoupler.jl/assets/9167485/ead271d5-26ad-4fe0-b93e-3b1f9702a99a)

**Comment by juliasloan25** [comment] 2024-05-22 01:20
I tried to recreate this from ClimaCoupler using the `slabplanet_albedo_temporal_map` configuration. The albedo looks fine after initialization, after 2 timesteps, and after 1 hour of coupled simulation. Here's the plot after one hour:
![albedo_after_1hour](https://github.com/CliMA/ClimaCoupler.jl/assets/51397186/b7703efb-7950-4895-ba35-dee127bb767f)

Was this seen in only the AMIP case before? If not, maybe this was fixed by updating to the most recent release of ClimaLand, which uses ClimaUtilities for regridding

**Comment by juliasloan25** [comment] 2024-05-22 01:33
I also tried the AMIP case (using the gpu_amip_albedo_temporal_map config, but running on CPU) and the albedo still looks fine after 1 hour:
![albedo_after_1hour_amip](https://github.com/CliMA/ClimaCoupler.jl/assets/51397186/e9e701c6-818e-4f3d-bd82-2e457e4812dc)

**Comment by Sbozzolo** [comment] 2024-05-22 03:06
If you have the scripts, can you also try with the `TempestRegridder`? I think the change in ClimaLand 0.12 was moving to the InterpolationsRegridder

**Comment by juliasloan25** [comment] 2024-05-23 20:37
I tried using ClimaLand v0.12.1 and `TempestRegridder`. This what the albedo looks like after initialization, using the `slabplanet_albedo_temporal_map` config with the resolution increased to 16 horizontal elements.
![slabplanet_tempest_albedo](https://github.com/CliMA/ClimaCoupler.jl/assets/51397186/2d7035a1-42a0-4486-aac1-be49909ac6cb)

It's very similar to the original picture Lenka showed, so it seems this is still something we need to investigate

**Comment by juliasloan25** [comment] 2024-05-23 21:06
I also took a look at the result of `ClimaLand.surface_albedo` in the ClimaLand temporal map experiment, and I see this after initialization:
![albedo_after_init](https://github.com/CliMA/ClimaCoupler.jl/assets/51397186/08b39f03-b672-4b27-8b5a-c2e7007b2efd)

and this after 50 days of simulation time:
![albedo_after_50days](https://github.com/CliMA/ClimaCoupler.jl/assets/51397186/29066e0d-60f7-4267-985f-9098e62346d5)

**Comment by Sbozzolo** [comment] 2024-05-23 21:57
Is your conclusion that it works in Land but not in the Coupler? Or are the white boxes a concern?

**Comment by juliasloan25** [comment] 2024-05-23 22:14
> Is your conclusion that it works in Land but not in the Coupler? Or are the white boxes a concern?

I don't know what conclusion to draw yet. I'm a bit concerned about the white boxes, and I'm also confused why these plots have them but the ones you sent earlier don't

**Comment by juliasloan25** [comment] 2024-05-24 21:35
Lenka and I realized that ClimaCoupler was creating a topography using `spacefillingcurve`, but ClimaLand/ClimaUtilities was not. This was probably leading to problems because the data was being read onto a space with a different layout from what was expected.

Here is the temporal map albedo after initialization, after `spacefillingcurve` has been removed from ClimaCoupler (see PR https://github.com/CliMA/ClimaCoupler.jl/pull/818 for changes):
![slabplanet_tempest_albedo_nospacefillingcurve](https://github.com/CliMA/ClimaCoupler.jl/assets/51397186/ed30cad7-1fb9-4f4b-bf33-66148a29fd2c)

ClimaAtmos uses `spacefillingcurve`, and we just need to all be consistent, so maybe the better solution is to use `spacefillingcurve` throughout all repos.

**Comment by Sbozzolo** [comment] 2024-05-30 00:53
I went back to ClimaLand 0.11, pre-ClimaUtilities, and found that the issue was already there:
![image](https://github.com/CliMA/ClimaCoupler.jl/assets/9167485/f1d446b8-2983-43cf-bf59-c26d55b7c4ab)

To reproduce, change `ClimaLand.jl/src/shared_utilities/Domains.jl`
```diff
- horztopology = ClimaCore.Topologies.Topology2D(comms_ctx, horzmesh)
+ horztopology = ClimaCore.Topologies.Topology2D(comms_ctx, horzmesh, ClimaCore.Topologies.spacefillingcurve(horzmesh))
```

Run
```julia
using ClimaLand, ClimaCoreTempestRemap, Plots, ClimaCorePlots
domain = ClimaLand.Domains.SphericalShell(radius=6e6, depth=1., nelements=(50, 10), npolynomial=3)
albedo = ClimaLand.Bucket.PrescribedBaregroundAlbedo{Float64}(1.0, domain.space.surface)
plot(albedo.α_bareground)
```
(cc: @sriharshakandala)

The issue is probably with ClimaUtilities.TempestRemapper (which inherited the land remapper) given that the ClimaCoupler is using ClimaCoreTempestRemap with spacefilledcurves, right?

**Comment by juliasloan25** [comment] 2024-06-04 17:31
comment copied from #818: 

> The problem is in `boundary_space` somehow. I created a horzspace from scratch from the coupler and it works. What I noticed is that the `boundary_space` mesh has a different `elemorder` compared to a fresh horzspace
> 
> ```
> julia> boundary_space.grid.topology.elemorder
> 2400-element Vector{CartesianIndex{3}}:
>  CartesianIndex(1, 1, 1)
> .....
> 
> julia> horzspace.grid.topology.elemorder
> CartesianIndices((20, 20, 6))
> ```
> 
> These are not equivalent.
> 
> Interestingly,
> 
> ```
> julia> extrema(parent(good) .- parent(bad))
> (0.0, 0.0)
> ```
> 
> where `good` and `bad` are albedo obtained using `horzspace` or `boundary_space` respectively.

ClimaAtmos and ClimaCoupler both create spaces using a `spacefillingcurve` (e.g. [here](https://github.com/CliMA/ClimaCoupler.jl/blob/f2f6a6e2f3df584674bb152a7ab2b5f36bcdaf29/src/Regridder.jl#L172-L176) in ClimaCoupler.Regridder), whereas ClimaLand and ClimaUtilities both create spaces without a `spacefillingcurve` (e.g. [here](https://github.com/CliMA/ClimaUtilities.jl/blob/ea7f2b353d2179738ee967d7245ad18cbc112114/ext/TempestRegridderExt.jl#L340-L345) in ClimaUtilities.TempestRegridder). This is why the two spaces have different element orders.

I had to add a TempestRemap GPU workaround in ClimaLand to force the regridding to happen on the CPU (this involves creating a new CPU context and space), and I noticed that if I created the undistributed space with a `spacefillingcurve`, `space_distributed == space_undistributed` was not true. This is why ClimaLand (and ClimaUtilities) don't use the `spacefillingcurve`. We should unify this across all repos, but I'm not sure which approach we should take

cc @sriharshakandala

**Comment by juliasloan25** [comment] 2024-06-17 22:49
Using the fix implemented in https://github.com/CliMA/ClimaUtilities.jl/pull/66, we can regrid the land albedo using `TempestRegridder` and get the following regridded field:
![amip_tempest_albedo_spacefillingcurve](https://github.com/CliMA/ClimaCoupler.jl/assets/51397186/0a12d223-0485-4092-ba6d-633889e47c02)

There are still some things that aren't ideal in this implementation (i.e. we still need `swap_space`) but it seems reliable for now. We will continue using `InterpolationsRegridder` as the default, but this fix will let us use TempestRemap if we want to.

The other fields that are currently regridded using TempestRemap (SST, SIC, CO2, land_area_fraction) will be investigated as part of https://github.com/CliMA/ClimaCoupler.jl/issues/860

**Closed by juliasloan25** 2024-06-17 22:49 UTC
Labels: bug, :fire: Urgent
