### ISSUE TITLE
Update ClimaAtmos to v0.11.0 in ClimaCoupler

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaCoupler.jl#281] opened 2023-04-24 21:13 UTC
# The Climate Modeling Alliance
### Purpose

We want to update ClimaCoupler so to use the latest ClimaAtmos version, v0.11.0 that was just released.

### Cost/Benefits/Risks
**Benefits:**
Using the latest ClimaAtmos version will keep the Coupler updated with the latest changes and will integrate the latest several improvements/fixes that were added to ClimaAtmos

**Costs:**
@valeriabarra 's time (up to 40% time)

**Risks:**
Updating the ClimaAtmos version in ClimaCoupler has shown challenges in the past. It took two people weeks to complete. We might face similar challenges: API changes will have to be carefully applied; ClimaAtmos may have changed the way boundary conditions and surface fluxes are defined and applied; tests/experiments should run and we should make sure that behavior-changing changes do not alter the physics of the results. 

### People and Personnel
- Lead: @valeriabarra 
- Potential Collaborators:
- Reviewers: @LenkaNovak , @charleskawczynski 

#### Part 1 (`experiments/AMIP/modular/` environment):
- Add `compat` entries to `experiments/AMIP/modular/Project.toml` so that we can use the package manager `Pkg` to update `ClimaAtmos` using non-breaking Compat entries
- Add/Update ClimaAtmos' relevant CLI options in [`cli_options.jl`](https://github.com/CliMA/ClimaCoupler.jl/blob/main/experiments/AMIP/modular/cli_options.jl)
- Make sure that [`ClimaComms.init`](https://github.com/CliMA/ClimaCoupler.jl/blob/61626e375b2500b04686210035a39ae879e3a87a/experiments/AMIP/modular/mpi/mpi_init.jl#L9) and `parsed_args` are not overridden 
- Components that might change in the [coupler_driver_modular.jl](https://github.com/CliMA/ClimaCoupler.jl/blob/main/experiments/AMIP/modular/coupler_driver_modular.jl): `horizontal space`, `flux_calculator` 
-  We'll also need to update `push_pull.jl` to exchange the required fields from the new ClimaAtmos cache
- Surface flux calculation: we need to call [this line](https://github.com/CliMA/ClimaAtmos.jl/blob/7c44950a13d6117505ba4d6badc879222ecc0033/src/tendencies/vertical_diffusion_boundary_layer.jl#L237) from the coupler (e.g. from the `push_pull.jl`); N.B. `flux_calculator.jl` should no longer be needed
- Use the regular CI Buildkite yml file for testing (this [job](https://github.com/CliMA/ClimaCoupler.jl/blob/main/.buildkite/pipeline.yml#L171) in particular)
#### Dependencies
Updating ClimaAtmos relies also on updating `ClimaLSM`. We need a release of `ClimaLSM` first.

#### Part 2 (top-level `ClimaCoupler.jl` environment):
This part will initially be on hold until the current work towards the AMIP configuration #276  (which involves some refactoring) will be finalized. Then we will apply similar changes to the top-level `ClimaCoupler.jl` environment

#### Part 3 (`test` environment):
After the top-level environment is updated, the `test` environment should also be updated and tested

### Inputs
Work package assigned directly from Tapio: "Update the version of ClimaAtmos in ClimaCoupler, updating for any API changes and ensuring examples work correctly."

### Results and Deliverables
- ClimaCoupler will use the latest ClimaAtmos v0.11.0 in the modular experiment environment 
- Code will be adapted/updated to accommodate any API changes
- The ClimaCoupler CI pipeline will be updated to test integration tests that will use the latest ClimaAtmos version to check correctness of behavior

##### week 1:
- [x] #284
- [x] Update to latest `ClimaLSM` release in `experiments/AMIP/modular/Project.toml` (need `ClimaLSM` release)

##### week 2:
- [x] #292
- [x] #297
- [x] #298

##### week 3:
- [x] Test ClimaAtmos v0.11.0 in CI pipeline 

##### week 4: 
- [x]  QA

Deadline: May 16th, 2023

### CC
@tapios @simonbyrne @cmbengue

**Comment by LenkaNovak** [comment] 2023-04-24 23:31
Looks good! Just a few additions/notes:
- components: we'll also need to update `push_pull.jl` to exchange the required fields from the new `ClimaAtmos` cache.
- surface flux calculation: we need to call [this line](https://github.com/CliMA/ClimaAtmos.jl/blob/7c44950a13d6117505ba4d6badc879222ecc0033/src/tendencies/vertical_diffusion_boundary_layer.jl#L237) from the coupler (e.g. from the `push_pull.jl`; N.B. `flux_calculator.jl` should no longer be needed)
- top level environment update: The test environment may also need to be updated at this stage for any underlying dependency updates. 
- timelines: (still WIP, or is part 2 going to be estimated later?) for part 1: this seems doable as is outlined. I'm much more optimistic, having looked in detail at the Atmos updates this afternoon! :)

**Comment by valeriabarra** [comment] 2023-04-25 00:06
Thanks Lenka. I will add those component details to the main SDI description for clarity/ease of reading. 

To answer your question about Part 2, I thought that that depends on the work being done as part of SDI #276 and there is no way we can speed that up by, say, copying/duplicating the entire top-level folder structure. But please correct/clarify if this can be rectified. Thanks

**Comment by LenkaNovak** [comment] 2023-04-25 04:26
Ok, makes sense. I mentioned this SDI there as well, so we can collaborate on this!

**Comment by charleskawczynski** [comment] 2023-04-25 17:55
> We want to update ClimaCoupler so to use the latest ClimaAtmos version, v0.10.0 that was just released.

The plan is to keep ClimaAtmos and the coupler synchronized over time, correct?

Here are some details that I think are necessary to point out in terms of sustainably maintaining their synchronization:
 - Use of `Pkg.develop`, `Pkg.activate`, `Pkg.instantiate`, and `Pkg.add` should be removed from all `.jl` files.
 - Add compat entries for all dependencies (as mentioned) in all of the environments

Managing / synchronizing many compat entries can be a bit cumbersome, but it's at least reproducible. I suggest using [CompatDevTools.jl](https://github.com/charleskawczynski/CompatDevTools.jl) if it's helpful to start compat entries on environments without them (but with a Manifest file), and using it to sync compat entries across environments.

I'm concerned with duplicating the environment to avoid disrupting other SDIs-- if `experiments/AMIP/modular/` is going to remain unchanged, then it may be even more difficult to maintain _multiple_ versions of dependencies instead of a single set of dependencies (similar to ClimaAtmos's old `ode_compat_examples`, which became unmaintainable because dependencies became incompatible). Changing dynamic to static environments (removing use of `Pkg.x` in `.jl` files) should not disrupt other peoples work, it should make everyone's workflow more smooth.

**Comment by LenkaNovak** [comment] 2023-04-26 17:02
Just to clarify from our chat yesterday, the first PR affecting `AMIP/modular/` will be in week 3?

**Comment by valeriabarra** [comment] 2023-04-26 17:28
> Just to clarify from our chat yesterday, the first PR affecting `AMIP/modular/` will be in week 3?

No, the first two PRs will work on the `AMIP/modular` environment already, by adding compat entries and tryin to update updatable package minor versions (sorry there was a typo in the task breakdown that was there from the first draft of the SDI, which I just fixed)

**Comment by valeriabarra** [comment] 2023-05-10 17:54
This SDI is complete

**Closed** 2023-05-11 21:21 UTC
Labels: :medal_sports: SDI
